server:
    error:
        include-stacktrace: never
    port: 8081
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bootdb?&createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
            ddl-auto: update
